spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daily_worker
    username: kamkendra
    password: myKam
    driver-class-name: com.mysql.cj.jdbc.Driver
    

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp    
    
server:
  port: 8060       

